
---
- hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios

  tasks:
  - name: IOS | Show clock
    ios_facts:
      gather_subset: all
    register: facts

  - debug: msg="{{ facts }}"